language: python
python: 
    - 3.3
    - 3.4
    - 3.5
    - nightly
    
install:
  pip install openpyxl
  
script:
  pwd
  cd LauguageParser
  python LanguageParse.py

deploy:
  provider: releases
  user:
    - secure: LMHEnKLV28sIP0K17hr+9+2igEiUVdaVZO4Bc5KglIhB/SbbXYaauiOxTqHYzGOs8HSOry1aVH4veqZJ8B+7eA7hiWM+cDSrImqbDlPCPn0vZAD94o9F4EnzDXHFb7scNuLBUn70Q5E9OqKjyYpogzdJP/7mxkb8yp+vfx08FNmz/JSpib3TL8Go7mgSW0d6StRwHCRls1HTB4urqVx/yv9BHifRGu/s/x6x+9Vac+yg2NEYyepVRtragGCq6Y3LcwdqNChxULREWegqm8zJOsjMrND7dcSBZdOoySHYJOuJRKgdUx0d41HqLzxmexz9rBORqR6RUsDxS7bi6Jpy2N9VkDl59f/9Y2FdtxYbifb8Fhcdka0w5iXfautEUzpuAnWoOYn8ORUeGRS8ORZkYFEQFIaikV+KxP3uePiejSKyXWW8QIvRPpgla9tXlqU1DJs97Sl5GwZYMoCZmsRSRRoOI6Hu6Wa3PzeFYycRPggtOaUUtATLHSvAOf+J8jJ6k50bmVmqyCN38HTpWj5TZiR7bb4HlvmHntQ+8c+DlN4R4fTCgtXSMsRdU4GjamgSUa/sw62NzYdtzti7l57+hUsMwvS/cqdwPJLEv54etpd1P3KLxm5sYcMPTGpZcVUuR4gX5A9L7WfRF54V9/aDAxjzGa/Tv48gmBc3C8QLi+o=
  password:
    - secure: LP5eBSw3mC1a4oa/DOpQovKsLdjQWOgnBoGL2lsc7Tm2J/khDagPChLhEfM4iBzGPpyBZE9iNyx9/77/tgQYtvQ2WKC3xbKAUxfhiwSAusnwNw4M8yuJxXb3U/nIuIIOALe+Gk8AhML+srX2S5krcyeCVN3T6xL44e4URG15YG3xGbpEiGoZ+504+MTwkwBmV/QIEhR+twydrF1dobpye32XeFP7OW+A31B8esXHZhwtQOkypdXLz/nhVFIKFlM4rF0kgOcaSKq1VA/oTpolkYK0AkgZvyQr/1fpWgdmsIpYM43MvvCenqGAtN06heTcHOEgpKk4UoF6aCSNqQ+eMGp/g9+oDlsshp7Uv82zxvmLy/TkWgY+WEylPyuvNJYt3LBnHsinWbbZNkFd3l4kokmF1y4s5Rks/KSZEWJiInc0SsuNDgQ3fwFbkS0RzXQZGa2mcbWfWqutw0Y1vRbOuhsKf64fGEwYgZ7rcpqiq7gm2u3WBzhWOSVzkcg/67G6m9LPaZJMXIcQtiREs0GQZpEYaSH/hvP8ZoZII4yWa1kCeen+XaqR83f8dQoVZwVNMxcPrgrbV11z+ppHQV4E8ERIrJigMVv7puAYiU0UArUIyX+RsQKCrrFv9r2wg80A865x6IuAKS+UROu+DuYvgoKwqu5Wk5/qtgoV0XSG1rg=
  file: Android/values/strings.xml
  skip_cleanup: true
  on:
    tags: true

