language: python
python: 
    - 3.3
    - 3.4
    - 3.5
    - nightly
    
install:
  pip install openpyxl
  
script:
  pwd
  cd LauguageParser
  python LanguageParse.py

deploy:
  provider: releases
  user:
    secure: "BXB/CHHZ9EO+jNk2tJpBSzw1o1QMAzSvp5K6X4usSigMXLEwUSqVJot4GOcM6sddMEdAJxfrbdbQMb+P/ILJOuZ8Q5d3o75o3vyzlrzkrbuPclwwOJ+9P1HXIWgdfkD27cdlFbFSnTwtWUkKPeYA9NIcLc6CbJS4ayZXv47n9ghTUXP6JXUwU7rxRlQNAbVSxvIYxvfPK2LtDENntSPnZKAd14S4EdnthH/bI7Pz52Ij0W+NSJDBy+HgVpQru6rWqC9ucVAbk1SkxOkQhB0hBTfHNQRugd9NoLXC1qlLJXiba9HmSiLvo5eoDYD+3k4Bt4dKr7UIrWTT5UJG18gbxGg16x79Am1NM5cV3PrYwBQUoeV835giyibYhBdACghJCG/6eyA/HD8/hHuCCEtDVStqDHx5gc/6jzh21Xd+GW61G2RSZNsatU7tNVdvbbqz4ViDCyeNHMrrLWNNJcxmkk35T1ytR68Hj9v3p0VdD2EcOl8X2im64VN8cfrjSREGRs6gfk70aMA7hZuG0z42fLFhrhB7QLMtpSxN+Tj0DBuF8KRJQAGKtuCM/KU744Hk275NYtlwQX5g9+dL3RRC9/wkLjAdpkurlRYf3LM9HSa+JVVAfCg5t576Ok/4NBTkaA0E9+QKRmaQ7FO4DpFHSsrhCMbmhhAdbG5ix7Pu1AQ="
  password:
    secure: "BIequHQUzmM4bZhMnwvp1zTN7YxvssvDjSTLHxQla+bPfT3nI7q9IFHw7twNkxMOyWT4J0GBjNPV8I341Y1rokq7aSFyF7OiFtp+PJ+h5DA0WzXAeiLPSRbzssmPJjqb3s/BrnryPzJ5Lm8iU3epAEekt7PxJpbTlzGvaFHFidofu9XYv8BEg9bICys5DRbadqI8bfc1tPa/uIo8sTKpwllwMjeLvZrQeg0AsvzBWr8cd/CvFNPptUKzBplUOEi5vOs67XF0ArVClo9/GIT9C9W1ThaiqclPHmr4+r9YRl0JxZ87+PUXrn0xd/ybI2palyFHqfwgm8iewYZuX60tUb03IlIR/1pS7MoZdlNOhAagLbbE6cVSzUPCm0oyhjqf6Smn1NIITPU/Cu89caDqlPXy4xFAnct48e6kKUcwGKr6KO/tTQgIyXhPLlG8pfbdKXMy2ew+EwXQfTy3SVjourRUQYYdPeuRLSjQBkYQ37rF/47J9+9atCjF5zLouV9DG+g7hc7WilTyKQTz608Yky5t23/UPkQkhNGZnfWT9AhsEV81zvx2CDE1DqliUyZKzwuQMD7zxnZYBIFxBhtFYWt+S6g7V+QgRFq2mm2h+adz6HZ14ViRgPMEr5nFh5Z0D2JI7HJuPWLlFuDIBXsbj5ykYuQ4XIxlW7JEdFP3ngY="
  file: Android/values/strings.xml
  skip_cleanup: true
  on:
    tags: false