language: python
python: 
    - 3.3
    - 3.4
    - 3.5
    - nightly
    
install:
  pip install openpyxl
  
script:
  pwd
  cd LauguageParser
  python LanguageParse.py
  git remote push origin https://{LukeLinXu:secure: "BIequHQUzmM4bZhMnwvp1zTN7YxvssvDjSTLHxQla+bPfT3nI7q9IFHw7twNkxMOyWT4J0GBjNPV8I341Y1rokq7aSFyF7OiFtp+PJ+h5DA0WzXAeiLPSRbzssmPJjqb3s/BrnryPzJ5Lm8iU3epAEekt7PxJpbTlzGvaFHFidofu9XYv8BEg9bICys5DRbadqI8bfc1tPa/uIo8sTKpwllwMjeLvZrQeg0AsvzBWr8cd/CvFNPptUKzBplUOEi5vOs67XF0ArVClo9/GIT9C9W1ThaiqclPHmr4+r9YRl0JxZ87+PUXrn0xd/ybI2palyFHqfwgm8iewYZuX60tUb03IlIR/1pS7MoZdlNOhAagLbbE6cVSzUPCm0oyhjqf6Smn1NIITPU/Cu89caDqlPXy4xFAnct48e6kKUcwGKr6KO/tTQgIyXhPLlG8pfbdKXMy2ew+EwXQfTy3SVjourRUQYYdPeuRLSjQBkYQ37rF/47J9+9atCjF5zLouV9DG+g7hc7WilTyKQTz608Yky5t23/UPkQkhNGZnfWT9AhsEV81zvx2CDE1DqliUyZKzwuQMD7zxnZYBIFxBhtFYWt+S6g7V+QgRFq2mm2h+adz6HZ14ViRgPMEr5nFh5Z0D2JI7HJuPWLlFuDIBXsbj5ykYuQ4XIxlW7JEdFP3ngY="
@}github.com/{LukeLinXu}/{LanguageParser}

